import test from 'node:test';
import assert from 'node:assert/strict';

import {
  assertVersion,
  syncCargoLock,
  syncCargoManifest,
  syncNodeAgentPackage,
  syncNodeClientVersionSource
} from '../scripts/sync-version.mjs';

test('validates semantic release versions', () => {
  assert.equal(assertVersion('1.2.3'), '1.2.3');
  assert.equal(assertVersion('1.2.3-rc.1+build.5'), '1.2.3-rc.1+build.5');
  assert.throws(() => assertVersion('1.2'), /invalid semantic version/);
});

test('synchronizes the Rust manifest and lock package versions', () => {
  const manifest = '[package]\nname = "coding-tools-mcp-desktop"\nversion = "0.1.31"\nedition = "2021"\n';
  const lock = '[[package]]\nname = "coding-tools-mcp-desktop"\nversion = "0.1.31"\ndependencies = []\n';

  assert.match(syncCargoManifest(manifest, '0.1.32'), /version = "0\.1\.32"/);
  assert.match(syncCargoLock(lock, '0.1.32'), /version = "0\.1\.32"/);
});

test('records the desktop Client compatibility version in the Node Agent', () => {
  const input = `${JSON.stringify({
    name: '@coding-tools/node-agent',
    version: '0.8.0',
    codingTools: { clientVersion: '0.1.31' }
  }, null, 2)}\n`;
  const synchronized = syncNodeAgentPackage(input, '0.1.32');
  assert.equal(JSON.parse(synchronized).codingTools.clientVersion, '0.1.32');
  assert.equal(syncNodeAgentPackage(synchronized, '0.1.32'), synchronized);
  assert.equal(
    syncNodeClientVersionSource('', '0.1.32'),
    "// Generated by scripts/sync-version.mjs. Do not edit manually.\nexport const CLIENT_COMPAT_VERSION = '0.1.32';\n"
  );
  assert.equal(
    syncNodeClientVersionSource(
      "// Generated by scripts/sync-version.mjs. Do not edit manually.\r\nexport const CLIENT_COMPAT_VERSION = '0.1.31';\r\n",
      '0.1.32'
    ),
    "// Generated by scripts/sync-version.mjs. Do not edit manually.\r\nexport const CLIENT_COMPAT_VERSION = '0.1.32';\r\n"
  );
});
