// Generated by scripts/sync-rust-catalog.mjs. Do not edit manually.
import type { ToolDefinition, ToolProfile } from './types.js';

export const rustCatalog: readonly ToolDefinition[] = [
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Harness status"
    },
    "description": "Return durable task, workspace, capability, and recovery status.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    },
    "name": "harness_status",
    "title": "Harness status"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Operation log"
    },
    "description": "Return Workspace-level operation history independent of Task state.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "cursor": {
          "default": 0,
          "minimum": 0,
          "type": "integer"
        },
        "errors_only": {
          "default": false,
          "type": "boolean"
        },
        "kind": {
          "maxLength": 64,
          "minLength": 1,
          "type": "string"
        },
        "limit": {
          "default": 50,
          "maximum": 200,
          "minimum": 1,
          "type": "integer"
        },
        "order": {
          "default": "desc",
          "enum": [
            "desc",
            "asc"
          ],
          "type": "string"
        },
        "since_ts_ms": {
          "minimum": 0,
          "type": "integer"
        },
        "tool": {
          "maxLength": 128,
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "operation_log",
    "title": "Operation log"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Server info"
    },
    "description": "Return server, workspace, auth, profile, and exposed-tool metadata.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    },
    "name": "server_info",
    "title": "Server info"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "List tool hub folders"
    },
    "description": "List folders configured in this tool hub and show the selected or default routing context.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    },
    "name": "list_workspace_folders",
    "title": "List tool hub folders"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Switch conversation folder"
    },
    "description": "Switch the current ChatGPT conversation to one allowed folder without reconnecting the shared MCP. Each folder keeps independent workspace history.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "folder_id": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "folder_id"
      ],
      "type": "object"
    },
    "name": "switch_workspace_folder",
    "title": "Switch conversation folder"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Query tool usage"
    },
    "description": "Safely query complete MCP tool-usage JSONL records and aggregate errors, latency, orchestration gaps, async child lifetimes, activity bursts, traffic, warnings, and sanitized command-pair parallelism statistics. Returns conflict/serialization evidence, Wilson confidence, and LLM-facing batching recommendations without reading a partial writer tail.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "aggregate": {
          "default": true,
          "type": "boolean"
        },
        "burst_idle_ms": {
          "default": 120000,
          "maximum": 3600000,
          "minimum": 1000,
          "type": "integer"
        },
        "errors_only": {
          "default": false,
          "type": "boolean"
        },
        "exclude_tools": {
          "default": [
            "query_tool_usage"
          ],
          "items": {
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        },
        "include_async_sessions": {
          "default": true,
          "type": "boolean"
        },
        "include_bursts": {
          "default": false,
          "type": "boolean"
        },
        "include_largest": {
          "default": false,
          "type": "boolean"
        },
        "include_payloads": {
          "default": false,
          "type": "boolean"
        },
        "include_performance": {
          "default": true,
          "type": "boolean"
        },
        "include_records": {
          "default": false,
          "type": "boolean"
        },
        "include_slowest": {
          "default": false,
          "type": "boolean"
        },
        "limit": {
          "default": 100,
          "maximum": 1000,
          "minimum": 1,
          "type": "integer"
        },
        "min_duration_ms": {
          "default": 0,
          "minimum": 0,
          "type": "integer"
        },
        "outcomes": {
          "default": [],
          "items": {
            "type": "string"
          },
          "maxItems": 20,
          "type": "array"
        },
        "scope": {
          "default": "current_runtime",
          "enum": [
            "current_runtime",
            "current_version",
            "all"
          ],
          "type": "string"
        },
        "since_ts_ms": {
          "default": 0,
          "minimum": 0,
          "type": "integer"
        },
        "sort_by": {
          "default": "calls",
          "enum": [
            "calls",
            "errors",
            "duration_ms",
            "p95_ms",
            "response_bytes",
            "request_bytes",
            "queue_wait_ms"
          ],
          "type": "string"
        },
        "tools": {
          "default": [],
          "items": {
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        },
        "top": {
          "default": 20,
          "maximum": 100,
          "minimum": 1,
          "type": "integer"
        }
      },
      "type": "object"
    },
    "name": "query_tool_usage",
    "title": "Query tool usage"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Initialize or restore development session"
    },
    "description": "At the start of every new ChatGPT conversation, call this exactly once before the first response, even when the user did not ask to restore. It creates the first history session when none exists, or returns ordered summaries plus the latest full handoff and resumes the current ChatGPT session without duplicates.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "create_if_missing": {
          "default": true,
          "type": "boolean"
        },
        "history_dir": {
          "default": "docs/history-session",
          "type": "string"
        },
        "session_key": {
          "minLength": 1,
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "workspace_root": {
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "history_session_bootstrap",
    "title": "Initialize or restore development session"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Save development checkpoint"
    },
    "description": "Save or update one idempotent, redacted development handoff. Pass session_key and expected_path exactly as returned by history_session_bootstrap so changing host metadata cannot redirect the checkpoint. The turn_id is optional and generated deterministically when omitted.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "decisions": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "expected_path": {
          "minLength": 1,
          "type": "string"
        },
        "files_changed": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "findings": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "history_dir": {
          "default": "docs/history-session",
          "type": "string"
        },
        "next_actions": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "notes": {
          "type": "string"
        },
        "remaining_issues": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "runtime_state": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "session_key": {
          "minLength": 1,
          "type": "string"
        },
        "tests": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "timestamp": {
          "type": "string"
        },
        "turn_id": {
          "minLength": 1,
          "type": "string"
        },
        "user_intent": {
          "type": "string"
        },
        "workspace_root": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "session_key",
        "expected_path"
      ],
      "type": "object"
    },
    "name": "history_session_checkpoint",
    "title": "Save development checkpoint"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Validate session archive"
    },
    "description": "Validate history numbering, files, session mappings, and optionally rebuild the derived index without deleting history.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "history_dir": {
          "default": "docs/history-session",
          "type": "string"
        },
        "repair": {
          "default": false,
          "type": "boolean"
        },
        "workspace_root": {
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "history_session_validate",
    "title": "Validate session archive"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Project state"
    },
    "description": "Return the current project, task, change, and verification state.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "max_files": {
          "default": 200,
          "maximum": 10000,
          "minimum": 1,
          "type": "integer"
        }
      },
      "type": "object"
    },
    "name": "project_state",
    "title": "Project state"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Start task"
    },
    "description": "Start a durable coding task and capture the workspace baseline.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "objective": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "objective"
      ],
      "type": "object"
    },
    "name": "start_task",
    "title": "Start task"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Update task"
    },
    "description": "Update task steps and durable progress.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "completed_steps": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "pending_steps": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "task_id": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "task_id"
      ],
      "type": "object"
    },
    "name": "update_task",
    "title": "Update task"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Pause task"
    },
    "description": "Pause the active coding task.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "task_id": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "task_id"
      ],
      "type": "object"
    },
    "name": "pause_task",
    "title": "Pause task"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Resume task"
    },
    "description": "Resume a paused or failed coding task.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "task_id": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "task_id"
      ],
      "type": "object"
    },
    "name": "resume_task",
    "title": "Resume task"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Finish task"
    },
    "description": "Finish a task with verification status and change summary.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "allow_unverified": {
          "default": false,
          "type": "boolean"
        },
        "summary": {
          "type": "string"
        },
        "task_id": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "task_id"
      ],
      "type": "object"
    },
    "name": "finish_task",
    "title": "Finish task"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Task context"
    },
    "description": "Return a bounded durable task context for a new conversation.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "max_bytes": {
          "default": 32768,
          "maximum": 131072,
          "minimum": 8192,
          "type": "integer"
        },
        "task_id": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "task_context",
    "title": "Task context"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "List task events"
    },
    "description": "Read task event history with pagination.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "cursor": {
          "default": 0,
          "minimum": 0,
          "type": "integer"
        },
        "limit": {
          "default": 50,
          "maximum": 200,
          "minimum": 1,
          "type": "integer"
        },
        "task_id": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "task_id"
      ],
      "type": "object"
    },
    "name": "list_task_events",
    "title": "List task events"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Change summary"
    },
    "description": "Explain what changed, why, and what evidence exists.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "change_id": {
          "type": "string"
        },
        "task_id": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "change_summary",
    "title": "Change summary"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Exec health check"
    },
    "description": "Verify the exec worker, session creation, command execution, and stdout/stderr capture.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    },
    "name": "exec_health_check",
    "title": "Exec health check"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Set default cwd"
    },
    "description": "Set the default cwd for relative tool paths inside the workspace.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "path": {
          "default": ".",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "set_default_cwd",
    "title": "Set default cwd"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Read file"
    },
    "description": "Read a UTF-8 text file slice inside the configured workspace.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "end_line": {
          "minimum": 1,
          "type": "integer"
        },
        "max_bytes": {
          "default": 131072,
          "maximum": 1048576,
          "minimum": 1,
          "type": "integer"
        },
        "path": {
          "minLength": 1,
          "type": "string"
        },
        "start_line": {
          "default": 1,
          "minimum": 1,
          "type": "integer"
        }
      },
      "required": [
        "path"
      ],
      "type": "object"
    },
    "name": "read_file",
    "title": "Read file"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Read many files"
    },
    "description": "Read multiple bounded UTF-8 file slices with hashes in one call.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "context_lines": {
          "default": 20,
          "maximum": 500,
          "minimum": 0,
          "type": "integer"
        },
        "items": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "end_line": {
                "minimum": 1,
                "type": "integer"
              },
              "max_bytes": {
                "maximum": 1048576,
                "minimum": 1,
                "type": "integer"
              },
              "path": {
                "minLength": 1,
                "type": "string"
              },
              "start_line": {
                "default": 1,
                "minimum": 1,
                "type": "integer"
              }
            },
            "required": [
              "path"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "type": "array"
        },
        "line_numbers": {
          "default": false,
          "type": "boolean"
        },
        "matches": {
          "description": "Search match objects containing path and line, or explicit ranges.",
          "items": {
            "additionalProperties": true,
            "properties": {
              "end_line": {
                "minimum": 1,
                "type": "integer"
              },
              "line": {
                "minimum": 1,
                "type": "integer"
              },
              "match_id": {
                "type": "string"
              },
              "max_bytes": {
                "maximum": 1048576,
                "minimum": 1,
                "type": "integer"
              },
              "path": {
                "minLength": 1,
                "type": "string"
              },
              "start_line": {
                "minimum": 1,
                "type": "integer"
              }
            },
            "required": [
              "path"
            ],
            "type": "object"
          },
          "maxItems": 500,
          "type": "array"
        },
        "max_bytes_per_file": {
          "default": 131072,
          "maximum": 1048576,
          "minimum": 1,
          "type": "integer"
        },
        "max_total_bytes": {
          "default": 262144,
          "maximum": 4194304,
          "minimum": 1,
          "type": "integer"
        },
        "merge_overlaps": {
          "default": true,
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "name": "read_many",
    "title": "Read many files"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Project map"
    },
    "description": "Summarize manifests, languages, entrypoints, tests, commands, and a bounded project tree.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "include_generated": {
          "default": false,
          "description": "Include generated dependency/build trees such as node_modules, target, dist, and build. .git remains excluded.",
          "type": "boolean"
        },
        "include_hidden": {
          "default": false,
          "type": "boolean"
        },
        "include_ignored": {
          "default": false,
          "type": "boolean"
        },
        "max_depth": {
          "default": 4,
          "maximum": 20,
          "minimum": 1,
          "type": "integer"
        },
        "max_entries": {
          "default": 1000,
          "maximum": 10000,
          "minimum": 1,
          "type": "integer"
        },
        "max_files": {
          "default": 10000,
          "maximum": 50000,
          "minimum": 1,
          "type": "integer"
        },
        "path": {
          "default": ".",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "project_map",
    "title": "Project map"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "List workspace entries"
    },
    "description": "List workspace files, directories, or symlinks using glob, depth, and entry-type filters.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "entry_types": {
          "default": [
            "file",
            "symlink"
          ],
          "items": {
            "enum": [
              "file",
              "directory",
              "symlink"
            ],
            "type": "string"
          },
          "type": "array"
        },
        "exclude_patterns": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "glob": {
          "description": "Alias for a single patterns entry",
          "type": "string"
        },
        "include_generated": {
          "default": false,
          "description": "Include generated dependency/build trees such as node_modules, target, dist, and build. .git remains excluded.",
          "type": "boolean"
        },
        "include_hidden": {
          "default": false,
          "type": "boolean"
        },
        "include_ignored": {
          "default": false,
          "type": "boolean"
        },
        "max_depth": {
          "default": 20,
          "maximum": 20,
          "minimum": 1,
          "type": "integer"
        },
        "max_results": {
          "default": 1000,
          "maximum": 50000,
          "minimum": 1,
          "type": "integer"
        },
        "path": {
          "default": ".",
          "type": "string"
        },
        "patterns": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "recursive": {
          "default": true,
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "name": "list_files",
    "title": "List workspace entries"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Search text"
    },
    "description": "Search UTF-8 workspace files for text or regex matches.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "case_sensitive": {
          "default": false,
          "type": "boolean"
        },
        "context_lines": {
          "default": 0,
          "description": "Values above 20 are normalized to 20",
          "maximum": 1000,
          "minimum": 0,
          "type": "integer"
        },
        "count_only": {
          "default": false,
          "type": "boolean"
        },
        "cursor": {
          "default": 0,
          "minimum": 0,
          "type": "integer"
        },
        "exclude_globs": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "filename_case_sensitive": {
          "default": false,
          "type": "boolean"
        },
        "filename_query": {
          "minLength": 1,
          "type": "string"
        },
        "filename_regex": {
          "default": false,
          "type": "boolean"
        },
        "files_only": {
          "default": false,
          "type": "boolean"
        },
        "glob": {
          "description": "Alias appended to include_globs",
          "type": "string"
        },
        "include_generated": {
          "default": false,
          "description": "Include generated dependency/build trees such as node_modules, target, dist, and build. .git remains excluded.",
          "type": "boolean"
        },
        "include_globs": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "include_hidden": {
          "default": false,
          "type": "boolean"
        },
        "include_ignored": {
          "default": false,
          "type": "boolean"
        },
        "max_file_bytes": {
          "default": 8388608,
          "maximum": 134217728,
          "minimum": 1024,
          "type": "integer"
        },
        "max_matches_per_file": {
          "maximum": 100000,
          "minimum": 1,
          "type": "integer"
        },
        "max_preview_bytes": {
          "default": 512,
          "description": "Normalized to the supported 64-4096 byte range",
          "maximum": 65536,
          "minimum": 1,
          "type": "integer"
        },
        "max_results": {
          "default": 200,
          "maximum": 10000,
          "minimum": 1,
          "type": "integer"
        },
        "path": {
          "default": ".",
          "type": "string"
        },
        "queries": {
          "items": {
            "oneOf": [
              {
                "minLength": 1,
                "type": "string"
              },
              {
                "additionalProperties": false,
                "properties": {
                  "case_sensitive": {
                    "type": "boolean"
                  },
                  "query": {
                    "minLength": 1,
                    "type": "string"
                  },
                  "regex": {
                    "type": "boolean"
                  }
                },
                "required": [
                  "query"
                ],
                "type": "object"
              }
            ]
          },
          "maxItems": 50,
          "type": "array"
        },
        "query": {
          "minLength": 1,
          "type": "string"
        },
        "regex": {
          "default": false,
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "name": "search_text",
    "title": "Search text"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Apply patch"
    },
    "description": "Apply a patch envelope transactionally inside the workspace.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "confirm": {
          "default": false,
          "type": "boolean"
        },
        "dry_run": {
          "default": false,
          "type": "boolean"
        },
        "expected_sha256": {
          "additionalProperties": {
            "maxLength": 64,
            "minLength": 64,
            "type": "string"
          },
          "type": "object"
        },
        "patch": {
          "minLength": 1,
          "type": "string"
        },
        "reason": {
          "default": "",
          "type": "string"
        }
      },
      "required": [
        "patch"
      ],
      "type": "object"
    },
    "name": "apply_patch",
    "title": "Apply patch"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Edit files"
    },
    "description": "Apply guarded text or line edits to one or more files as one atomic transaction. Text, context, and line targeting are selected through edit parameters while preserving each file's newline style.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "dry_run": {
          "default": false,
          "type": "boolean"
        },
        "files": {
          "items": {
            "additionalProperties": false,
            "oneOf": [
              {
                "required": [
                  "edits"
                ]
              },
              {
                "required": [
                  "apply_proposal"
                ]
              }
            ],
            "properties": {
              "apply_proposal": {
                "additionalProperties": false,
                "properties": {
                  "patch": {
                    "description": "Optional economical unified diff limited to one file and one hunk, applied only to the proposal replacement text.",
                    "maxLength": 65536,
                    "type": "string"
                  },
                  "proposal_id": {
                    "minLength": 1,
                    "type": "string"
                  },
                  "replacement": {
                    "description": "Optional complete final replacement for the proposal candidate region. Mutually exclusive with patch.",
                    "maxLength": 131072,
                    "type": "string"
                  }
                },
                "required": [
                  "proposal_id"
                ],
                "type": "object"
              },
              "edits": {
                "items": {
                  "oneOf": [
                    {
                      "additionalProperties": false,
                      "properties": {
                        "after_context": {
                          "type": "string"
                        },
                        "before_context": {
                          "type": "string"
                        },
                        "end_line": {
                          "minimum": 1,
                          "type": "integer"
                        },
                        "expected_occurrences": {
                          "default": 1,
                          "minimum": 1,
                          "type": "integer"
                        },
                        "match_mode": {
                          "default": "exact",
                          "description": "exact requires identical content except CRLF/LF line endings; whitespace additionally tolerates whitespace differences. Inserted and replacement text is normalized to the target file's newline style.",
                          "enum": [
                            "exact",
                            "whitespace"
                          ],
                          "type": "string"
                        },
                        "new_text": {
                          "type": "string"
                        },
                        "old_text": {
                          "minLength": 1,
                          "type": "string"
                        },
                        "start_line": {
                          "minimum": 1,
                          "type": "integer"
                        },
                        "type": {
                          "enum": [
                            "replace"
                          ],
                          "type": "string"
                        }
                      },
                      "required": [
                        "type",
                        "old_text",
                        "new_text"
                      ],
                      "type": "object"
                    },
                    {
                      "additionalProperties": false,
                      "properties": {
                        "after_context": {
                          "type": "string"
                        },
                        "anchor": {
                          "minLength": 1,
                          "type": "string"
                        },
                        "before_context": {
                          "type": "string"
                        },
                        "end_line": {
                          "minimum": 1,
                          "type": "integer"
                        },
                        "expected_occurrences": {
                          "default": 1,
                          "minimum": 1,
                          "type": "integer"
                        },
                        "match_mode": {
                          "default": "exact",
                          "description": "exact requires identical content except CRLF/LF line endings; whitespace additionally tolerates whitespace differences. Inserted and replacement text is normalized to the target file's newline style.",
                          "enum": [
                            "exact",
                            "whitespace"
                          ],
                          "type": "string"
                        },
                        "start_line": {
                          "minimum": 1,
                          "type": "integer"
                        },
                        "text": {
                          "minLength": 1,
                          "type": "string"
                        },
                        "type": {
                          "enum": [
                            "insert_before"
                          ],
                          "type": "string"
                        }
                      },
                      "required": [
                        "type",
                        "anchor",
                        "text"
                      ],
                      "type": "object"
                    },
                    {
                      "additionalProperties": false,
                      "properties": {
                        "after_context": {
                          "type": "string"
                        },
                        "anchor": {
                          "minLength": 1,
                          "type": "string"
                        },
                        "before_context": {
                          "type": "string"
                        },
                        "end_line": {
                          "minimum": 1,
                          "type": "integer"
                        },
                        "expected_occurrences": {
                          "default": 1,
                          "minimum": 1,
                          "type": "integer"
                        },
                        "match_mode": {
                          "default": "exact",
                          "description": "exact requires identical content except CRLF/LF line endings; whitespace additionally tolerates whitespace differences. Inserted and replacement text is normalized to the target file's newline style.",
                          "enum": [
                            "exact",
                            "whitespace"
                          ],
                          "type": "string"
                        },
                        "start_line": {
                          "minimum": 1,
                          "type": "integer"
                        },
                        "text": {
                          "minLength": 1,
                          "type": "string"
                        },
                        "type": {
                          "enum": [
                            "insert_after"
                          ],
                          "type": "string"
                        }
                      },
                      "required": [
                        "type",
                        "anchor",
                        "text"
                      ],
                      "type": "object"
                    },
                    {
                      "additionalProperties": false,
                      "properties": {
                        "end_line": {
                          "minimum": 1,
                          "type": "integer"
                        },
                        "expected_text": {
                          "type": "string"
                        },
                        "new_text": {
                          "type": "string"
                        },
                        "start_line": {
                          "minimum": 1,
                          "type": "integer"
                        },
                        "type": {
                          "enum": [
                            "replace_lines"
                          ],
                          "type": "string"
                        }
                      },
                      "required": [
                        "type",
                        "start_line",
                        "end_line",
                        "new_text"
                      ],
                      "type": "object"
                    },
                    {
                      "additionalProperties": false,
                      "properties": {
                        "end_line": {
                          "minimum": 1,
                          "type": "integer"
                        },
                        "expected_text": {
                          "type": "string"
                        },
                        "start_line": {
                          "minimum": 1,
                          "type": "integer"
                        },
                        "type": {
                          "enum": [
                            "delete_lines"
                          ],
                          "type": "string"
                        }
                      },
                      "required": [
                        "type",
                        "start_line",
                        "end_line"
                      ],
                      "type": "object"
                    }
                  ]
                },
                "maxItems": 100,
                "minItems": 1,
                "type": "array"
              },
              "expected_sha256": {
                "maxLength": 64,
                "minLength": 64,
                "type": "string"
              },
              "path": {
                "minLength": 1,
                "type": "string"
              }
            },
            "required": [
              "path"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array"
        },
        "reason": {
          "default": "",
          "type": "string"
        }
      },
      "required": [
        "files"
      ],
      "type": "object"
    },
    "name": "edit",
    "title": "Edit files"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "File operations"
    },
    "description": "Create, delete, copy, move, or create directories with transactional preflight.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "confirm": {
          "default": false,
          "type": "boolean"
        },
        "dry_run": {
          "default": false,
          "type": "boolean"
        },
        "operations": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "content": {
                "type": "string"
              },
              "destination": {
                "minLength": 1,
                "type": "string"
              },
              "expected_sha256": {
                "maxLength": 64,
                "minLength": 64,
                "type": "string"
              },
              "overwrite": {
                "default": false,
                "type": "boolean"
              },
              "path": {
                "minLength": 1,
                "type": "string"
              },
              "type": {
                "enum": [
                  "create",
                  "delete",
                  "copy",
                  "move",
                  "mkdir"
                ],
                "type": "string"
              }
            },
            "required": [
              "type",
              "path"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array"
        },
        "reason": {
          "default": "",
          "type": "string"
        }
      },
      "required": [
        "operations"
      ],
      "type": "object"
    },
    "name": "file_ops",
    "title": "File operations"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Format files"
    },
    "description": "Plan, check, or apply multi-language formatting in an isolated mirror with bounded diffs and guarded workspace writes.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "confirm": {
          "default": false,
          "type": "boolean"
        },
        "exclude_patterns": {
          "items": {
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        },
        "expected_sha256": {
          "additionalProperties": {
            "maxLength": 64,
            "minLength": 64,
            "type": "string"
          },
          "maxProperties": 10000,
          "type": "object"
        },
        "formatter": {
          "default": "auto",
          "description": "auto or a registered formatter adapter ID",
          "type": "string"
        },
        "include_patterns": {
          "items": {
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        },
        "max_diff_bytes": {
          "default": 262144,
          "maximum": 1048576,
          "minimum": 1024,
          "type": "integer"
        },
        "max_files": {
          "default": 500,
          "maximum": 10000,
          "minimum": 1,
          "type": "integer"
        },
        "mode": {
          "default": "plan",
          "enum": [
            "plan",
            "check",
            "apply"
          ],
          "type": "string"
        },
        "paths": {
          "description": "Explicit workspace-relative files or directories. Optional for changed, staged, and project scopes.",
          "items": {
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 10000,
          "type": "array"
        },
        "reason": {
          "default": "",
          "type": "string"
        },
        "scope": {
          "default": "files",
          "enum": [
            "files",
            "changed",
            "staged",
            "project"
          ],
          "type": "string"
        },
        "strict": {
          "default": false,
          "type": "boolean"
        },
        "timeout_ms": {
          "default": 120000,
          "maximum": 600000,
          "minimum": 1,
          "type": "integer"
        }
      },
      "type": "object"
    },
    "name": "format_files",
    "title": "Format files"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Check patch"
    },
    "description": "Validate a patch without changing the workspace.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "patch": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "patch"
      ],
      "type": "object"
    },
    "name": "patch_check",
    "title": "Check patch"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": true,
      "readOnlyHint": false,
      "title": "Execute command"
    },
    "description": "Run a bounded command in the workspace under runtime policy. When a session is retained, continue with wait_command using the returned next_actions arguments.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "args": {
          "default": [],
          "items": {
            "type": "string"
          },
          "maxItems": 1000,
          "type": "array"
        },
        "cmd": {
          "description": "Legacy command string or explicit shell command",
          "minLength": 1,
          "type": "string"
        },
        "confirm": {
          "default": false,
          "type": "boolean"
        },
        "cursor": {
          "default": 0,
          "minimum": 0,
          "type": "integer"
        },
        "deduplicate": {
          "description": "Coalesce identical retries. Defaults to true for safe Cargo check, test, build, and format commands.",
          "type": "boolean"
        },
        "env": {
          "additionalProperties": {
            "maxLength": 4096,
            "type": "string"
          },
          "maxProperties": 64,
          "type": "object"
        },
        "filesystem_scope": {
          "default": "workspace",
          "enum": [
            "workspace"
          ],
          "type": "string"
        },
        "lock_group": {
          "description": "Shared resource lock. Cargo commands automatically derive a lock from their target directory.",
          "maxLength": 128,
          "minLength": 1,
          "type": "string"
        },
        "max_output_bytes": {
          "default": 65536,
          "maximum": 1048576,
          "minimum": 1024,
          "type": "integer"
        },
        "operation_id": {
          "description": "Stable idempotency key used to reattach retries instead of spawning a duplicate process.",
          "maxLength": 128,
          "minLength": 1,
          "type": "string"
        },
        "output_mode": {
          "default": "tail",
          "enum": [
            "delta",
            "tail",
            "all",
            "none",
            "summary"
          ],
          "type": "string"
        },
        "post_checks": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "args": {
                "default": [],
                "items": {
                  "type": "string"
                },
                "maxItems": 1000,
                "type": "array"
              },
              "cmd": {
                "minLength": 1,
                "type": "string"
              },
              "confirm": {
                "default": false,
                "type": "boolean"
              },
              "env": {
                "additionalProperties": {
                  "maxLength": 4096,
                  "type": "string"
                },
                "maxProperties": 64,
                "type": "object"
              },
              "expected_exit_code": {
                "default": 0,
                "type": "integer"
              },
              "max_output_bytes": {
                "default": 16384,
                "maximum": 1048576,
                "minimum": 1,
                "type": "integer"
              },
              "name": {
                "maxLength": 256,
                "type": "string"
              },
              "program": {
                "minLength": 1,
                "type": "string"
              },
              "remove_env": {
                "items": {
                  "type": "string"
                },
                "maxItems": 64,
                "type": "array"
              },
              "script": {
                "minLength": 1,
                "type": "string"
              },
              "shell": {
                "default": "none",
                "enum": [
                  "none",
                  "cmd",
                  "powershell",
                  "sh"
                ],
                "type": "string"
              },
              "timeout_ms": {
                "default": 30000,
                "maximum": 3600000,
                "minimum": 1,
                "type": "integer"
              }
            },
            "type": "object"
          },
          "maxItems": 16,
          "type": "array"
        },
        "program": {
          "description": "Executable name or workspace-local path for shell-free execution",
          "minLength": 1,
          "type": "string"
        },
        "reason": {
          "default": "",
          "type": "string"
        },
        "remove_env": {
          "items": {
            "type": "string"
          },
          "maxItems": 64,
          "type": "array"
        },
        "script": {
          "description": "Structured shell script body; requires shell other than none",
          "minLength": 1,
          "type": "string"
        },
        "shell": {
          "default": "none",
          "enum": [
            "none",
            "cmd",
            "powershell",
            "sh"
          ],
          "type": "string"
        },
        "stdin": {
          "default": "",
          "type": "string"
        },
        "tail_lines": {
          "default": 100,
          "maximum": 10000,
          "minimum": 1,
          "type": "integer"
        },
        "timeout_ms": {
          "default": 30000,
          "maximum": 3600000,
          "minimum": 1,
          "type": "integer"
        },
        "tty": {
          "default": false,
          "type": "boolean"
        },
        "workdir": {
          "default": ".",
          "type": "string"
        },
        "yield_time_ms": {
          "default": 1000,
          "maximum": 30000,
          "minimum": 0,
          "type": "integer"
        }
      },
      "type": "object"
    },
    "name": "exec_command",
    "title": "Execute command"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": true,
      "readOnlyHint": false,
      "title": "Execute command graph"
    },
    "description": "Run up to 256 structured exec_command requests. Auto mode combines non-bypassable safety rules, inferred or named Cargo/Git/Node resource locks, and sanitized historical command-pair statistics. Unknown pairs stay sequential until repeated explicit parallel runs establish a safe Wilson confidence bound; conflicts or lock serialization automatically reduce concurrency. Prefer this over repeated exec_command calls when two or more commands can overlap.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "default": "run",
          "description": "Run or reattach by default; status returns immediately, cancel terminates active graph children, and forget releases a completed retained graph immediately.",
          "enum": [
            "run",
            "status",
            "cancel",
            "forget"
          ],
          "type": "string"
        },
        "commands": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "args": {
                "default": [],
                "items": {
                  "type": "string"
                },
                "maxItems": 1000,
                "type": "array"
              },
              "cmd": {
                "minLength": 1,
                "type": "string"
              },
              "confirm": {
                "default": false,
                "type": "boolean"
              },
              "deduplicate": {
                "description": "Coalesce identical retries. Defaults to true for safe Cargo check, test, build, and format commands.",
                "type": "boolean"
              },
              "depends_on": {
                "default": [],
                "description": "Command IDs that must succeed before this command can run in dag mode",
                "items": {
                  "maxLength": 128,
                  "minLength": 1,
                  "type": "string"
                },
                "maxItems": 256,
                "type": "array"
              },
              "env": {
                "additionalProperties": {
                  "maxLength": 4096,
                  "type": "string"
                },
                "maxProperties": 64,
                "type": "object"
              },
              "filesystem_scope": {
                "default": "workspace",
                "enum": [
                  "workspace"
                ],
                "type": "string"
              },
              "id": {
                "description": "Stable command identifier used by DAG dependencies",
                "maxLength": 128,
                "minLength": 1,
                "type": "string"
              },
              "lock_group": {
                "description": "Shared named resource lock such as cargo-target, node-generated, or git-index",
                "maxLength": 128,
                "minLength": 1,
                "type": "string"
              },
              "max_output_bytes": {
                "default": 65536,
                "maximum": 1048576,
                "minimum": 1024,
                "type": "integer"
              },
              "operation_id": {
                "description": "Stable idempotency key. Retries with the same command reattach to the retained session.",
                "maxLength": 128,
                "minLength": 1,
                "type": "string"
              },
              "output_mode": {
                "default": "tail",
                "enum": [
                  "tail",
                  "none",
                  "summary"
                ],
                "type": "string"
              },
              "program": {
                "minLength": 1,
                "type": "string"
              },
              "reason": {
                "default": "",
                "type": "string"
              },
              "remove_env": {
                "items": {
                  "type": "string"
                },
                "maxItems": 64,
                "type": "array"
              },
              "script": {
                "description": "Structured shell script body; requires shell other than none",
                "minLength": 1,
                "type": "string"
              },
              "shell": {
                "default": "none",
                "enum": [
                  "none",
                  "cmd",
                  "powershell",
                  "sh"
                ],
                "type": "string"
              },
              "stdin": {
                "default": "",
                "type": "string"
              },
              "timeout_ms": {
                "default": 30000,
                "maximum": 3600000,
                "minimum": 1,
                "type": "integer"
              },
              "tty": {
                "default": false,
                "type": "boolean"
              },
              "workdir": {
                "default": ".",
                "type": "string"
              },
              "yield_time_ms": {
                "default": 30000,
                "maximum": 30000,
                "minimum": 0,
                "type": "integer"
              }
            },
            "type": "object"
          },
          "maxItems": 256,
          "minItems": 1,
          "type": "array"
        },
        "max_parallel": {
          "description": "Maximum concurrently running batch commands. Auto mode bounds the requested value by 8, workspace process admission, and historical resource-serialization recommendations.",
          "maximum": 256,
          "minimum": 1,
          "type": "integer"
        },
        "mode": {
          "default": "auto",
          "description": "Execution scheduler. Auto uses dependencies, hard safety rules, resource locks, and historical pair statistics. Unknown command pairs remain sequential until explicit parallel observations provide enough safe evidence; explicit parallel is never silently overridden.",
          "enum": [
            "auto",
            "sequential",
            "parallel",
            "dag"
          ],
          "type": "string"
        },
        "operation_id": {
          "description": "Stable retained graph identifier. Reuse it without commands to reattach to the same exec_many graph instead of starting duplicate commands.",
          "maxLength": 128,
          "minLength": 1,
          "type": "string"
        },
        "reason": {
          "default": "",
          "description": "Optional reason recorded when cancelling a retained graph.",
          "type": "string"
        },
        "result_mode": {
          "description": "Controls per-command result detail. When omitted, run/reattach preserves full results while status/cancel use compact summaries to avoid repeating large stdout/stderr payloads.",
          "enum": [
            "full",
            "summary",
            "none"
          ],
          "type": "string"
        },
        "stop_on_error": {
          "default": true,
          "type": "boolean"
        },
        "yield_time_ms": {
          "default": 30000,
          "description": "How long this exec_many call waits for graph completion before returning retained progress. The graph continues running after this window.",
          "maximum": 30000,
          "minimum": 0,
          "type": "integer"
        }
      },
      "type": "object"
    },
    "name": "exec_many",
    "title": "Execute command graph"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Wait for command"
    },
    "description": "Wait for an exec_command session to produce new sequenced output, exit, or finish verification without client-side polling.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "cursor": {
          "default": 0,
          "minimum": 0,
          "type": "integer"
        },
        "heartbeat_ms": {
          "default": 0,
          "description": "Deprecated compatibility field. Accepted but ignored for application wait timing; MCP transport heartbeats keep long requests alive automatically.",
          "maximum": 30000,
          "minimum": 0,
          "type": "integer"
        },
        "max_output_bytes": {
          "default": 65536,
          "maximum": 1048576,
          "minimum": 1,
          "type": "integer"
        },
        "output_mode": {
          "default": "delta",
          "enum": [
            "delta",
            "tail",
            "all",
            "none",
            "summary"
          ],
          "type": "string"
        },
        "session_id": {
          "minLength": 1,
          "type": "string"
        },
        "tail_lines": {
          "default": 100,
          "maximum": 10000,
          "minimum": 1,
          "type": "integer"
        },
        "timeout_ms": {
          "default": 30000,
          "description": "Server-side event wait. Use until=finalized with a longer timeout for quiet long-running commands to reduce repeated polling.",
          "maximum": 120000,
          "minimum": 0,
          "type": "integer"
        },
        "until": {
          "default": "output_or_exit",
          "enum": [
            "output_or_exit",
            "exit",
            "finalized"
          ],
          "type": "string"
        }
      },
      "required": [
        "session_id"
      ],
      "type": "object"
    },
    "name": "wait_command",
    "title": "Wait for command"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Resolve command operation"
    },
    "description": "Reattach to a retained command by operation_id or command_fingerprint without starting a duplicate process.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "command_fingerprint": {
          "maxLength": 64,
          "minLength": 64,
          "type": "string"
        },
        "cursor": {
          "default": 0,
          "minimum": 0,
          "type": "integer"
        },
        "max_output_bytes": {
          "default": 65536,
          "maximum": 1048576,
          "minimum": 1,
          "type": "integer"
        },
        "operation_id": {
          "maxLength": 128,
          "minLength": 1,
          "type": "string"
        },
        "output_mode": {
          "default": "tail",
          "enum": [
            "delta",
            "tail",
            "all",
            "none",
            "summary"
          ],
          "type": "string"
        },
        "tail_lines": {
          "default": 100,
          "maximum": 10000,
          "minimum": 1,
          "type": "integer"
        }
      },
      "type": "object"
    },
    "name": "resolve_operation",
    "title": "Resolve command operation"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "List command sessions"
    },
    "description": "List bounded retained command sessions for recovery, diagnosis, and orphan cleanup.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "include_finalized": {
          "default": true,
          "type": "boolean"
        },
        "limit": {
          "default": 100,
          "maximum": 1000,
          "minimum": 1,
          "type": "integer"
        },
        "status": {
          "enum": [
            "running",
            "verifying",
            "exited",
            "timed_out",
            "killed"
          ],
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "list_sessions",
    "title": "List command sessions"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Send command input"
    },
    "description": "Write stdin or close stdin for a running command session without waiting for output.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "chars": {
          "default": "",
          "type": "string"
        },
        "close_stdin": {
          "default": false,
          "type": "boolean"
        },
        "session_id": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "session_id"
      ],
      "type": "object"
    },
    "name": "send_input",
    "title": "Send command input"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Kill session"
    },
    "description": "Terminate a server-managed running command session.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "max_output_bytes": {
          "default": 65536,
          "maximum": 1048576,
          "minimum": 1,
          "type": "integer"
        },
        "session_id": {
          "minLength": 1,
          "type": "string"
        },
        "signal": {
          "default": "TERM",
          "enum": [
            "TERM",
            "KILL",
            "INT"
          ],
          "type": "string"
        },
        "wait_ms": {
          "default": 5000,
          "maximum": 30000,
          "minimum": 0,
          "type": "integer"
        }
      },
      "required": [
        "session_id"
      ],
      "type": "object"
    },
    "name": "kill_session",
    "title": "Kill session"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Read output"
    },
    "description": "Read retained stdout or stderr by output_ref with per-stream byte offset pagination.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "limit": {
          "default": 4096,
          "maximum": 1048576,
          "minimum": 1,
          "type": "integer"
        },
        "offset": {
          "default": 0,
          "minimum": 0,
          "type": "integer"
        },
        "output_ref": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "output_ref"
      ],
      "type": "object"
    },
    "name": "read_output",
    "title": "Read output"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Git status"
    },
    "description": "Return git working tree status for the workspace.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "include_untracked": {
          "default": true,
          "type": "boolean"
        },
        "max_entries": {
          "default": 1000,
          "maximum": 10000,
          "minimum": 1,
          "type": "integer"
        },
        "path": {
          "default": ".",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "git_status",
    "title": "Git status"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Git diff"
    },
    "description": "Return unified git diff for workspace changes.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "context_lines": {
          "default": 3,
          "description": "Values above 20 are normalized to 20",
          "maximum": 1000,
          "minimum": 0,
          "type": "integer"
        },
        "max_bytes": {
          "default": 262144,
          "maximum": 1048576,
          "minimum": 1024,
          "type": "integer"
        },
        "paths": {
          "default": [],
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "staged": {
          "default": false,
          "type": "boolean"
        },
        "unstaged": {
          "default": true,
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "name": "git_diff",
    "title": "Git diff"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Git log"
    },
    "description": "Return recent git commits with bounded structured metadata.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "max_count": {
          "default": 20,
          "maximum": 100,
          "minimum": 1,
          "type": "integer"
        },
        "path": {
          "default": ".",
          "type": "string"
        },
        "ref": {
          "default": "HEAD",
          "type": "string"
        },
        "skip": {
          "default": 0,
          "maximum": 10000,
          "minimum": 0,
          "type": "integer"
        }
      },
      "type": "object"
    },
    "name": "git_log",
    "title": "Git log"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Git show"
    },
    "description": "Return bounded git show output for a revision.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "context_lines": {
          "default": 3,
          "description": "Values above 20 are normalized to 20",
          "maximum": 1000,
          "minimum": 0,
          "type": "integer"
        },
        "include_diff": {
          "default": true,
          "type": "boolean"
        },
        "max_bytes": {
          "default": 262144,
          "maximum": 1048576,
          "minimum": 1,
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "paths": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "rev": {
          "default": "HEAD",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "git_show",
    "title": "Git show"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Git blame"
    },
    "description": "Return bounded git blame metadata for a workspace file.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "end_line": {
          "minimum": 1,
          "type": "integer"
        },
        "max_lines": {
          "default": 200,
          "maximum": 1000,
          "minimum": 1,
          "type": "integer"
        },
        "path": {
          "minLength": 1,
          "type": "string"
        },
        "rev": {
          "type": "string"
        },
        "start_line": {
          "default": 1,
          "minimum": 1,
          "type": "integer"
        }
      },
      "required": [
        "path"
      ],
      "type": "object"
    },
    "name": "git_blame",
    "title": "Git blame"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Git branch"
    },
    "description": "Create, switch, or delete a Git branch with expected-HEAD guards.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "enum": [
            "create",
            "switch",
            "delete"
          ],
          "type": "string"
        },
        "confirm": {
          "default": false,
          "type": "boolean"
        },
        "dry_run": {
          "default": false,
          "type": "boolean"
        },
        "expected_head": {
          "type": "string"
        },
        "expected_repo_fingerprint": {
          "maxLength": 64,
          "minLength": 64,
          "type": "string"
        },
        "force": {
          "default": false,
          "type": "boolean"
        },
        "name": {
          "minLength": 1,
          "type": "string"
        },
        "reason": {
          "default": "",
          "type": "string"
        },
        "repo_path": {
          "default": ".",
          "description": "Workspace-relative Git repository or linked worktree root",
          "type": "string"
        },
        "start_point": {
          "type": "string"
        },
        "switch": {
          "default": true,
          "type": "boolean"
        }
      },
      "required": [
        "action",
        "name"
      ],
      "type": "object"
    },
    "name": "git_branch",
    "title": "Git branch"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Git stage"
    },
    "description": "Stage selected paths or all workspace changes with structured results.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "all": {
          "default": false,
          "type": "boolean"
        },
        "dry_run": {
          "default": false,
          "type": "boolean"
        },
        "expected_head": {
          "type": "string"
        },
        "expected_repo_fingerprint": {
          "maxLength": 64,
          "minLength": 64,
          "type": "string"
        },
        "paths": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "reason": {
          "default": "",
          "type": "string"
        },
        "repo_path": {
          "default": ".",
          "description": "Workspace-relative Git repository or linked worktree root",
          "type": "string"
        }
      },
      "type": "object"
    },
    "name": "git_stage",
    "title": "Git stage"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Git commit"
    },
    "description": "Create a guarded Git commit and return the new commit and repository status.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "all": {
          "default": false,
          "type": "boolean"
        },
        "allow_empty": {
          "default": false,
          "type": "boolean"
        },
        "dry_run": {
          "default": false,
          "type": "boolean"
        },
        "expected_head": {
          "type": "string"
        },
        "expected_repo_fingerprint": {
          "maxLength": 64,
          "minLength": 64,
          "type": "string"
        },
        "message": {
          "maxLength": 10000,
          "minLength": 1,
          "type": "string"
        },
        "paths": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "reason": {
          "default": "",
          "type": "string"
        },
        "repo_path": {
          "default": ".",
          "description": "Workspace-relative Git repository or linked worktree root",
          "type": "string"
        },
        "require_clean_index_before": {
          "type": "boolean"
        }
      },
      "required": [
        "message"
      ],
      "type": "object"
    },
    "name": "git_commit",
    "title": "Git commit"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true,
      "readOnlyHint": false,
      "title": "Git push"
    },
    "description": "Push the current or selected branch to a remote with expected-HEAD guards and structured authentication errors.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "branch": {
          "description": "Defaults to the current branch; required for detached HEAD.",
          "minLength": 1,
          "type": "string"
        },
        "dry_run": {
          "default": false,
          "type": "boolean"
        },
        "expected_head": {
          "type": "string"
        },
        "expected_repo_fingerprint": {
          "maxLength": 64,
          "minLength": 64,
          "type": "string"
        },
        "reason": {
          "default": "",
          "type": "string"
        },
        "remote": {
          "default": "origin",
          "minLength": 1,
          "type": "string"
        },
        "repo_path": {
          "default": ".",
          "description": "Workspace-relative Git repository or linked worktree root",
          "type": "string"
        },
        "set_upstream": {
          "default": false,
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "name": "git_push",
    "title": "Git push"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Git restore"
    },
    "description": "Restore or unstage selected paths with explicit confirmation.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "confirm": {
          "default": false,
          "type": "boolean"
        },
        "dry_run": {
          "default": false,
          "type": "boolean"
        },
        "expected_head": {
          "type": "string"
        },
        "expected_repo_fingerprint": {
          "maxLength": 64,
          "minLength": 64,
          "type": "string"
        },
        "paths": {
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "type": "array"
        },
        "reason": {
          "default": "",
          "type": "string"
        },
        "repo_path": {
          "default": ".",
          "description": "Workspace-relative Git repository or linked worktree root",
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "staged": {
          "default": false,
          "type": "boolean"
        },
        "worktree": {
          "type": "boolean"
        }
      },
      "required": [
        "paths"
      ],
      "type": "object"
    },
    "name": "git_restore",
    "title": "Git restore"
  },
  {
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
      "title": "Approve and resume operation"
    },
    "description": "Approve and immediately resume one pending permission-gated operation.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "approve": {
          "default": false,
          "type": "boolean"
        },
        "arguments": {
          "additionalProperties": true,
          "type": "object"
        },
        "confirm": {
          "default": false,
          "type": "boolean"
        },
        "permission": {
          "enum": [
            "network",
            "destructive_command",
            "long_timeout",
            "sensitive_env",
            "shell_expansion",
            "inline_script",
            "privileged_executable",
            "write_generated_or_ignored"
          ],
          "type": "string"
        },
        "reason": {
          "minLength": 1,
          "type": "string"
        },
        "resume_id": {
          "minLength": 1,
          "type": "string"
        },
        "scope": {
          "default": "once",
          "enum": [
            "once",
            "session"
          ],
          "type": "string"
        },
        "tool_name": {
          "enum": [
            "exec_command",
            "apply_patch",
            "git_push"
          ],
          "type": "string"
        },
        "ttl_seconds": {
          "default": 300,
          "maximum": 3600,
          "minimum": 1,
          "type": "integer"
        }
      },
      "type": "object"
    },
    "name": "request_permissions",
    "title": "Approve and resume operation"
  },
  {
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "View image"
    },
    "description": "Return a workspace image as MCP image content.",
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "auto_resize": {
          "default": true,
          "type": "boolean"
        },
        "max_bytes": {
          "default": 5242880,
          "maximum": 10485760,
          "minimum": 1024,
          "type": "integer"
        },
        "max_height": {
          "default": 2000,
          "maximum": 10000,
          "minimum": 1,
          "type": "integer"
        },
        "max_width": {
          "default": 2000,
          "maximum": 10000,
          "minimum": 1,
          "type": "integer"
        },
        "output": {
          "default": "mcp_image",
          "enum": [
            "mcp_image",
            "data_url"
          ],
          "type": "string"
        },
        "path": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "path"
      ],
      "type": "object"
    },
    "name": "view_image",
    "title": "View image"
  }
];
export const rustToolNamesByProfile: Readonly<Record<ToolProfile, readonly string[]>> = {
  "advanced": [
    "harness_status",
    "operation_log",
    "server_info",
    "list_workspace_folders",
    "switch_workspace_folder",
    "query_tool_usage",
    "history_session_bootstrap",
    "history_session_checkpoint",
    "history_session_validate",
    "project_state",
    "start_task",
    "update_task",
    "pause_task",
    "resume_task",
    "finish_task",
    "task_context",
    "list_task_events",
    "change_summary",
    "exec_health_check",
    "set_default_cwd",
    "read_file",
    "read_many",
    "project_map",
    "list_files",
    "search_text",
    "apply_patch",
    "edit",
    "file_ops",
    "format_files",
    "patch_check",
    "exec_command",
    "exec_many",
    "wait_command",
    "resolve_operation",
    "list_sessions",
    "send_input",
    "kill_session",
    "read_output",
    "git_status",
    "git_diff",
    "git_log",
    "git_show",
    "git_blame",
    "git_branch",
    "git_stage",
    "git_commit",
    "git_push",
    "git_restore",
    "request_permissions",
    "view_image"
  ],
  "read-only": [
    "server_info",
    "list_workspace_folders",
    "query_tool_usage",
    "read_file",
    "read_many",
    "project_map",
    "list_files",
    "search_text",
    "wait_command",
    "resolve_operation",
    "list_sessions",
    "read_output",
    "git_status",
    "git_diff",
    "git_log",
    "git_show",
    "git_blame",
    "view_image"
  ],
  "compat-readonly-all": [
    "harness_status",
    "operation_log",
    "server_info",
    "list_workspace_folders",
    "switch_workspace_folder",
    "query_tool_usage",
    "history_session_bootstrap",
    "history_session_checkpoint",
    "history_session_validate",
    "project_state",
    "start_task",
    "update_task",
    "pause_task",
    "resume_task",
    "finish_task",
    "task_context",
    "list_task_events",
    "change_summary",
    "exec_health_check",
    "set_default_cwd",
    "read_file",
    "read_many",
    "project_map",
    "list_files",
    "search_text",
    "apply_patch",
    "edit",
    "file_ops",
    "format_files",
    "patch_check",
    "exec_command",
    "exec_many",
    "wait_command",
    "resolve_operation",
    "list_sessions",
    "send_input",
    "kill_session",
    "read_output",
    "git_status",
    "git_diff",
    "git_log",
    "git_show",
    "git_blame",
    "git_branch",
    "git_stage",
    "git_commit",
    "git_push",
    "git_restore",
    "request_permissions",
    "view_image"
  ],
  "guarded-core": [
    "server_info",
    "list_workspace_folders",
    "switch_workspace_folder",
    "query_tool_usage",
    "history_session_bootstrap",
    "history_session_checkpoint",
    "set_default_cwd",
    "read_file",
    "read_many",
    "project_map",
    "list_files",
    "search_text",
    "apply_patch",
    "edit",
    "file_ops",
    "format_files",
    "exec_command",
    "exec_many",
    "wait_command",
    "resolve_operation",
    "list_sessions",
    "send_input",
    "kill_session",
    "read_output",
    "git_status",
    "git_diff",
    "git_log",
    "git_show",
    "git_blame",
    "git_branch",
    "git_stage",
    "git_commit",
    "git_push",
    "git_restore",
    "request_permissions",
    "view_image"
  ],
  "trusted-core": [
    "server_info",
    "list_workspace_folders",
    "switch_workspace_folder",
    "query_tool_usage",
    "history_session_bootstrap",
    "history_session_checkpoint",
    "set_default_cwd",
    "read_file",
    "read_many",
    "project_map",
    "list_files",
    "search_text",
    "apply_patch",
    "edit",
    "file_ops",
    "format_files",
    "exec_command",
    "exec_many",
    "wait_command",
    "resolve_operation",
    "list_sessions",
    "send_input",
    "kill_session",
    "read_output",
    "git_status",
    "git_diff",
    "git_log",
    "git_show",
    "git_blame",
    "git_branch",
    "git_stage",
    "git_commit",
    "git_push",
    "git_restore",
    "view_image"
  ]
};
export const rustToolAnnotationOverridesByProfile: Readonly<Record<ToolProfile, Readonly<Record<string, ToolDefinition['annotations']>>>> = {
  "advanced": {},
  "read-only": {},
  "compat-readonly-all": {
    "switch_workspace_folder": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Switch conversation folder"
    },
    "history_session_bootstrap": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Initialize or restore development session"
    },
    "history_session_checkpoint": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Save development checkpoint"
    },
    "history_session_validate": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Validate session archive"
    },
    "start_task": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Start task"
    },
    "update_task": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Update task"
    },
    "pause_task": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Pause task"
    },
    "resume_task": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Resume task"
    },
    "finish_task": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Finish task"
    },
    "set_default_cwd": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Set default cwd"
    },
    "apply_patch": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Apply patch"
    },
    "edit": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Edit files"
    },
    "file_ops": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "File operations"
    },
    "format_files": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Format files"
    },
    "exec_command": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Execute command"
    },
    "exec_many": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Execute command graph"
    },
    "send_input": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Send command input"
    },
    "kill_session": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Kill session"
    },
    "git_branch": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Git branch"
    },
    "git_stage": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Git stage"
    },
    "git_commit": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Git commit"
    },
    "git_push": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Git push"
    },
    "git_restore": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Git restore"
    },
    "request_permissions": {
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
      "title": "Approve and resume operation"
    }
  },
  "guarded-core": {},
  "trusted-core": {}
};
export const rustToolsetRevisionByProfile: Readonly<Record<ToolProfile, string>> = {
  "advanced": "cd6a370aaabd35ab",
  "read-only": "d3e63ccd8e6c0b19",
  "compat-readonly-all": "a93ab448d6add11b",
  "guarded-core": "8da48d46317ec605",
  "trusted-core": "d105229c9e8b32d2"
};
export const rustBehavioralParityFixtures: Readonly<Record<string, unknown>> = {
  "execution_limits": {
    "active_sessions": 512,
    "blocking_admission": 128,
    "command_timeout_absolute_max_ms": 3600000,
    "command_timeout_default_ms": 1800000,
    "global_blocking_admission": 1024,
    "global_process_admission": 512,
    "process_admission": 64
  },
  "mcp_transport": {
    "latest_protocol_version": "2025-11-25",
    "stream_channel_capacity": 2,
    "stream_heartbeat_interval_ms": 10000,
    "supported_protocol_versions": [
      "2025-11-25",
      "2025-06-18",
      "2025-03-26"
    ]
  },
  "process_start": {
    "circuit_breaker_delay_ms": 3000,
    "circuit_breaker_threshold": 3,
    "failure_window_ms": 10000,
    "retry_delays_ms": [
      250,
      750,
      1500
    ],
    "start_interval_ms": 75,
    "startup_probe_ms": 125,
    "startup_slots": 4,
    "status_dll_init_failed": -1073741502
  },
  "tunnel": {
    "demand_hint_ttl_ms": 3000,
    "local_connect_timeout_ms": 10000
  },
  "workspace": {
    "max_conversation_contexts": 128
  }
};
